title = 'ICPC Bolivia'
baseURL = 'https://icpc-bolivia.netlify.app/'
languageCode = 'es-bo'
theme = "ananke"
resourceDir = "../resources"

DefaultContentLanguage = "es"
SectionPagesMenu = "main"
Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[languages]
  [languages.es]
    title = "ICPC Bolivia"
    weight = 1
    contentDir = "content/es"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  text_color = ""
  author = "ICPC Bolivia"
  favicon = "images/favicon.png"
  site_logo = ""
  description = "Sitio oficial de ICPC Bolivia"
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-navy"
  recent_posts_number = 3
  custom_css = ["css/styles.css"]

[[params.ananke_socials]]
name = "facebook"
url = "https://www.facebook.com/icpc.bolivia.oficial"

[markup.goldmark.renderer]
unsafe= true
